server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: microservices-inventory
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/db_inventory_keycloak?createIfNotExists=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: docker
    password: docker
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    io.github.emfsilva.controller: DEBUG
    org.hibernate: DEBUG
    org: INFO

